# Generated by Django 4.2.6 on 2023-10-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_log', '0004_alter_review_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
