# Generated by Django 4.2.6 on 2023-10-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_log', '0005_delete_entry_delete_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='topic',
            new_name='book',
        ),
    ]
